apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-external-idp-ldap

resources:
  - ../base
  - openldap.yaml

patchesStrategicMerge:
  - tenant.yaml
  - storage-user.yaml
