---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: myminio
  namespace: minio-tenant
spec:
  log:
    db:
      serviceAccountName: tenant-log-db-sa
  prometheus:
    serviceAccountName: tenant-prometheus-sa
