apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenant-certmanager-kes

resources:
  - certificates.yaml
  - vault.yaml
  - ../tenant-kes-encryption

patchesStrategicMerge:
  - tenant.yaml

